export const CAPABILITY_ROLES = ["backend", "fullstack", "ai", "pm", "tpm"] as const;
export type CapabilityRole = (typeof CAPABILITY_ROLES)[number];

export const CAPABILITY_DEMAND = ["adjacent", "recurring", "core"] as const;
export type CapabilityDemand = (typeof CAPABILITY_DEMAND)[number];

export type RoleDemand = Record<CapabilityRole, 0 | 1 | 2 | 3>;

export interface CapabilityDomain {
  id: string;
  title: string;
  titleZh: string;
  purpose: string;
}

export interface CapabilityNode {
  id: string;
  domain: string;
  title: string;
  titleZh: string;
  /** What this capability lets someone do, rather than a topic definition. */
  ability: string;
  /** Observable standard for claiming the capability. */
  mastery: string;
  /** An artifact or result that can prove it. */
  proof: string;
  technologies: string[];
  roles: RoleDemand;
  prerequisites: string[];
}

const roles = (backend: 0 | 1 | 2 | 3, fullstack: 0 | 1 | 2 | 3, ai: 0 | 1 | 2 | 3, pm: 0 | 1 | 2 | 3, tpm: 0 | 1 | 2 | 3): RoleDemand => ({
  backend,
  fullstack,
  ai,
  pm,
  tpm,
});

const node = (
  id: string,
  domain: string,
  title: string,
  titleZh: string,
  ability: string,
  mastery: string,
  proof: string,
  technologies: string[],
  roleDemand: RoleDemand,
  prerequisites: string[] = [],
): CapabilityNode => ({
  id,
  domain,
  title,
  titleZh,
  ability,
  mastery,
  proof,
  technologies,
  roles: roleDemand,
  prerequisites,
});

export const CAPABILITY_DOMAINS: readonly CapabilityDomain[] = [
  {
    id: "foundations",
    title: "Engineering foundations",
    titleZh: "工程基础",
    purpose: "理解代码为什么正确、系统为什么会失败；这是所有技术方向共享的地基。",
  },
  {
    id: "product-core",
    title: "Product reasoning",
    titleZh: "产品判断",
    purpose: "判断该解决什么问题、为谁解决，以及如何知道解决得对不对。",
  },
  {
    id: "backend-data",
    title: "Backend & data",
    titleZh: "后端与数据",
    purpose: "把业务规则变成可靠的接口、数据模型和后台执行系统。",
  },
  {
    id: "frontend",
    title: "Product engineering",
    titleZh: "前端与产品工程",
    purpose: "把能力做成用户能理解、能控制、愿意反复使用的完整体验。",
  },
  {
    id: "platform",
    title: "Platform & operations",
    titleZh: "平台与生产系统",
    purpose: "让系统在真实流量、故障、安全和团队协作约束下持续运行。",
  },
  {
    id: "ai-systems",
    title: "AI systems",
    titleZh: "AI 系统",
    purpose: "把概率模型变成可评估、可控制、可维护的生产能力。",
  },
  {
    id: "product-leadership",
    title: "Product leadership",
    titleZh: "产品领导力",
    purpose: "连接用户价值、模型能力、工程约束和商业结果，做出清晰取舍。",
  },
  {
    id: "program-delivery",
    title: "Program & field delivery",
    titleZh: "项目群与落地交付",
    purpose: "让跨团队、跨公司、高依赖的技术项目可预测地落地并被采用。",
  },
] as const;

export const CAPABILITY_NODES: readonly CapabilityNode[] = [
  // Engineering foundations
  node(
    "problem-solving",
    "foundations",
    "Algorithms & data structures",
    "算法与数据结构",
    "把问题归约成数据结构、状态和复杂度约束，而不是靠试错堆代码。",
    "能解释方案不变量，比较时间/空间复杂度，并识别输入规模改变后首先失效的部分。",
    "一个带基准、复杂度说明和边界测试的实现，而不是只通过样例的题解。",
    ["arrays", "hash maps", "trees", "graphs", "dynamic programming", "complexity"],
    roles(3, 3, 3, 1, 1),
  ),
  node(
    "language-runtime",
    "foundations",
    "Language & runtime models",
    "语言与运行时模型",
    "理解类型、内存、异步和错误传播，能预测代码的运行行为。",
    "能解释所用语言的并发模型、对象生命周期、类型边界和常见性能陷阱。",
    "在 Python、TypeScript、Go 或 Java 中诊断一次真实的并发、内存或类型问题。",
    ["Python", "TypeScript", "Go", "Java", "typing", "async/await", "memory"],
    roles(3, 3, 3, 1, 2),
    ["problem-solving"],
  ),
  node(
    "networking-http",
    "foundations",
    "Networking & HTTP",
    "网络与 HTTP",
    "沿请求路径定位 DNS、TLS、连接、代理、缓存和协议层问题。",
    "能从浏览器或客户端一直追到服务端，解释超时、重试、连接复用和状态码语义。",
    "一次带 trace/curl 证据的网络故障复盘，或一个正确处理缓存与重试的客户端。",
    ["DNS", "TCP", "TLS", "HTTP", "WebSocket", "SSE", "gRPC"],
    roles(3, 3, 2, 1, 2),
    ["language-runtime"],
  ),
  node(
    "os-concurrency",
    "foundations",
    "OS & concurrency",
    "操作系统与并发",
    "理解进程、线程、锁、文件和调度如何约束服务行为。",
    "能识别 race、deadlock、资源泄漏与阻塞 I/O，并选择合适的并发原语。",
    "复现并修复一次竞争条件、队列阻塞或进程资源泄漏。",
    ["processes", "threads", "locks", "event loops", "filesystems", "Linux"],
    roles(3, 2, 3, 0, 2),
    ["language-runtime"],
  ),
  node(
    "software-design",
    "foundations",
    "Software design",
    "软件设计",
    "把变化隔离在清晰边界内，让业务规则不被框架和供应商绑死。",
    "能说明模块职责、依赖方向、接口深度，以及何时不值得增加抽象。",
    "一份小型设计文档和对应重构，显示边界更清楚、测试更容易而不是文件更多。",
    ["modules", "interfaces", "domain modeling", "dependency inversion", "design docs"],
    roles(3, 3, 3, 2, 2),
    ["language-runtime"],
  ),
  node(
    "engineering-quality",
    "foundations",
    "Engineering quality & collaboration",
    "工程质量与协作",
    "通过版本控制、评审、文档和自动检查，让团队安全地共同修改系统。",
    "能写可评审的小变更，给出有依据的 review，并把重复错误固化成自动检查。",
    "一个结构清晰的 PR：范围小、测试明确、迁移和回滚说明完整。",
    ["Git", "code review", "documentation", "linting", "static analysis", "ADRs"],
    roles(3, 3, 3, 2, 3),
    ["software-design"],
  ),

  // Product reasoning
  node(
    "problem-framing",
    "product-core",
    "Problem framing",
    "问题定义",
    "把模糊诉求改写成用户、场景、约束、成功条件和非目标。",
    "能区分症状、请求和根因，并在方案出现前写出可证伪的问题陈述。",
    "一页 problem brief，包含目标用户、当前行为、痛点证据、约束和不做什么。",
    ["problem statements", "assumptions", "constraints", "non-goals"],
    roles(1, 2, 2, 3, 3),
  ),
  node(
    "customer-discovery",
    "product-core",
    "Customer discovery",
    "用户与客户研究",
    "从访谈、行为和支持信号中识别高价值工作流，而不是收集功能愿望。",
    "能设计不诱导的访谈，区分陈述偏好与真实行为，并合成重复模式。",
    "访谈记录、机会地图和由证据支持的优先问题，不是意见汇总。",
    ["interviews", "workflow observation", "support signals", "opportunity mapping"],
    roles(0, 2, 2, 3, 2),
    ["problem-framing"],
  ),
  node(
    "requirements",
    "product-core",
    "Requirements & acceptance",
    "需求与验收标准",
    "把用户结果翻译成可实现、可测试、边界明确的行为。",
    "能写清主流程、失败流程、权限、数据和非功能需求，并让工程与设计做出同一件事。",
    "一份包含示例、边界、验收标准和开放问题的 spec。",
    ["PRDs", "user stories", "acceptance criteria", "non-functional requirements"],
    roles(1, 2, 2, 3, 3),
    ["problem-framing"],
  ),
  node(
    "prioritization",
    "product-core",
    "Prioritization & roadmap",
    "优先级与路线图",
    "在价值、风险、成本、依赖和学习速度之间做明确取舍。",
    "能解释为什么现在做、为什么不做，以及什么新证据会改变决定。",
    "一张围绕结果而非功能日期组织的 roadmap，附决策记录和被拒选项。",
    ["roadmaps", "opportunity sizing", "RICE", "decision logs", "sequencing"],
    roles(0, 1, 1, 3, 3),
    ["requirements"],
  ),
  node(
    "product-metrics",
    "product-core",
    "Metrics & instrumentation",
    "指标与埋点",
    "把产品目标变成可观测行为，分清结果指标、先导指标和护栏指标。",
    "能定义事件模型、指标口径和分群，发现一个好看的数字为什么会误导。",
    "指标树、事件字典和能回答真实产品问题的 SQL/dashboard。",
    ["SQL", "event taxonomy", "funnels", "retention", "KPI trees", "dashboards"],
    roles(1, 2, 2, 3, 3),
    ["requirements"],
  ),
  node(
    "experimentation",
    "product-core",
    "Experimentation",
    "实验与因果判断",
    "设计能减少不确定性的实验，并正确解释线上与离线结果。",
    "能定义假设、样本、成功阈值和护栏，识别偏差、泄漏和多重比较。",
    "一份实验设计与结果分析，包含没有显著提升时的决策。",
    ["A/B testing", "statistics", "confidence intervals", "guardrail metrics", "feature flags"],
    roles(0, 1, 2, 3, 2),
    ["product-metrics"],
  ),
  node(
    "ux-judgment",
    "product-core",
    "UX & interaction judgment",
    "体验与交互判断",
    "把复杂系统状态转成用户能理解、控制和恢复的交互。",
    "能处理空态、加载、错误、权限、撤销与渐进披露，并用研究验证而非个人审美裁决。",
    "一个经过可用性测试的流程，展示如何处理失败和不确定状态。",
    ["Figma", "prototyping", "usability testing", "information architecture", "accessibility"],
    roles(0, 3, 2, 3, 1),
    ["customer-discovery", "requirements"],
  ),
  node(
    "business-value",
    "product-core",
    "Business value & ROI",
    "商业价值与 ROI",
    "把技术改善连接到收入、成本、风险、速度或战略优势。",
    "能写出基线、收益机制、采用成本和敏感性范围，不用虚假的精确数字包装判断。",
    "一个有假设、有区间、有事后复盘的 business case。",
    ["unit economics", "ROI", "TCO", "pricing", "market analysis"],
    roles(0, 1, 2, 3, 3),
    ["product-metrics"],
  ),

  // Backend & data
  node(
    "api-contracts",
    "backend-data",
    "API design & contracts",
    "API 设计与契约",
    "设计稳定、可演进、失败语义明确的服务边界。",
    "能处理版本、幂等、分页、限流、错误模型和兼容性，并从调用者体验判断接口质量。",
    "一份 OpenAPI/Proto 契约、契约测试和兼容性变更示例。",
    ["REST", "OpenAPI", "GraphQL", "gRPC", "webhooks", "idempotency"],
    roles(3, 3, 3, 2, 2),
    ["networking-http", "requirements", "software-design"],
  ),
  node(
    "identity-security",
    "backend-data",
    "Identity & application security",
    "身份与应用安全",
    "让每次访问都具有可验证身份、最小权限和可审计边界。",
    "能区分 authentication/authorization，设计 session/token 生命周期，并防住常见 Web 与 API 攻击。",
    "一个带 RBAC/ABAC、密钥管理、审计日志和威胁模型的服务。",
    ["OAuth 2.0", "OIDC", "sessions", "JWT", "RBAC", "OWASP"],
    roles(3, 3, 3, 1, 2),
    ["api-contracts"],
  ),
  node(
    "relational-modeling",
    "backend-data",
    "Relational data modeling",
    "关系数据建模",
    "把业务不变量放进 schema、约束、索引和查询，而不是只放在应用约定里。",
    "能从访问模式设计表和索引，解释范式取舍，并用执行计划定位慢查询。",
    "ER 图、迁移、约束、索引理由和真实查询计划。",
    ["PostgreSQL", "MySQL", "SQL", "indexes", "migrations", "query plans"],
    roles(3, 3, 2, 1, 1),
    ["software-design", "requirements"],
  ),
  node(
    "transactions-consistency",
    "backend-data",
    "Transactions & consistency",
    "事务与一致性",
    "在并发更新、重试和部分失败下维持数据不变量。",
    "能选择隔离级别，识别 lost update/phantom，设计幂等写入、outbox 或补偿。",
    "一个可复现并发故障及其修复，附一致性边界说明。",
    ["ACID", "isolation levels", "optimistic locking", "outbox", "sagas"],
    roles(3, 2, 2, 1, 2),
    ["relational-modeling", "os-concurrency"],
  ),
  node(
    "caching",
    "backend-data",
    "Caching",
    "缓存",
    "用缓存换取延迟或吞吐，同时明确失效、一致性和击穿成本。",
    "能选择 cache-aside/write-through，设计 key、TTL、失效和降级，并用命中率验证价值。",
    "带命中率、p95 延迟和失效测试的 Redis/CDN 缓存实现。",
    ["Redis", "CDN", "HTTP caching", "TTL", "cache invalidation"],
    roles(3, 2, 2, 0, 1),
    ["api-contracts", "relational-modeling"],
  ),
  node(
    "async-messaging",
    "backend-data",
    "Async jobs & messaging",
    "异步任务与消息系统",
    "把长任务和跨服务工作变成可重试、可观测、可恢复的后台流程。",
    "能处理 at-least-once、顺序、重复、毒消息、backpressure 和 dead-letter queue。",
    "一个经故障注入验证的 worker/queue 流程，展示重复投递不会破坏结果。",
    ["Kafka", "SQS", "Pub/Sub", "RabbitMQ", "Celery", "queues"],
    roles(3, 2, 3, 1, 2),
    ["transactions-consistency", "os-concurrency"],
  ),
  node(
    "backend-services",
    "backend-data",
    "Service implementation",
    "后端服务实现",
    "把接口、业务规则、数据和外部依赖组装成可维护的生产服务。",
    "能保持 domain/transport/storage 边界，处理配置、超时、错误、依赖注入和优雅关闭。",
    "一个有文档、测试、部署和运行手册的 FastAPI/Node/Go 服务。",
    ["FastAPI", "Node.js", "NestJS", "Go", "Pydantic", "service layers"],
    roles(3, 3, 3, 1, 2),
    ["api-contracts", "relational-modeling", "engineering-quality"],
  ),
  node(
    "testing-strategy",
    "backend-data",
    "Testing strategy",
    "测试策略",
    "用最小但有力的测试组合保护行为边界，而不是追求覆盖率数字。",
    "能分配 unit/integration/contract/e2e 测试，控制测试数据，并让失败指向真正原因。",
    "一个会阻止真实回归、运行稳定且能在 CI 中快速定位失败的测试套件。",
    ["pytest", "Jest", "contract tests", "integration tests", "test doubles", "property tests"],
    roles(3, 3, 3, 1, 2),
    ["backend-services"],
  ),
  node(
    "data-pipelines",
    "backend-data",
    "Data pipelines",
    "数据管道",
    "可靠地采集、转换、验证和提供可追溯的数据。",
    "能设计 batch/streaming、schema 演进、质量检查、回填、血缘和重跑语义。",
    "一个可重跑、有数据质量断言和 lineage 的 ETL/ELT pipeline。",
    ["Pandas", "Spark", "Airflow", "dbt", "Kafka", "BigQuery"],
    roles(2, 1, 3, 2, 2),
    ["relational-modeling", "async-messaging"],
  ),

  // Frontend & product engineering
  node(
    "web-platform",
    "frontend",
    "Web platform fundamentals",
    "Web 平台基础",
    "直接使用浏览器语义、布局、事件、网络和可访问性能力构建界面。",
    "能解释 DOM、CSS layout、事件传播、表单和浏览器安全边界，不依赖框架猜行为。",
    "一个不用 UI 框架也具备键盘操作、响应式布局和正确表单语义的页面。",
    ["HTML", "CSS", "DOM", "forms", "browser APIs", "responsive design"],
    roles(0, 3, 1, 1, 0),
    ["language-runtime", "networking-http"],
  ),
  node(
    "react-architecture",
    "frontend",
    "React application architecture",
    "React 应用架构",
    "把组件、状态、数据获取和副作用组织成可推理的单向系统。",
    "能为每份状态选择 server/URL/component owner，避免重复源和 effect 驱动的同步。",
    "一个状态所有权清晰、刷新可恢复、没有不必要全局 store 的 React/Next.js 功能。",
    ["React", "Next.js", "TypeScript", "Server Components", "hooks"],
    roles(0, 3, 1, 1, 0),
    ["web-platform", "software-design"],
  ),
  node(
    "client-data-state",
    "frontend",
    "Client data & state",
    "客户端数据与状态",
    "在缓存、乐观更新、并发请求和离线/失败状态下保持 UI 与服务端一致。",
    "能处理 stale data、race、取消、重试、回滚和 URL 可分享状态。",
    "一个在慢网、重复提交和请求乱序下仍正确的交互流程。",
    ["fetch", "SWR", "React Query", "URL state", "optimistic UI"],
    roles(0, 3, 1, 1, 0),
    ["react-architecture", "api-contracts"],
  ),
  node(
    "design-accessibility",
    "frontend",
    "Design systems & accessibility",
    "设计系统与无障碍",
    "用一致组件和语义让产品跨页面、设备和输入方式保持可用。",
    "能建立 token/variants，满足键盘、焦点、对比度、screen reader 和 reduced motion。",
    "一组经过 axe/键盘/小屏验证的可复用组件，而不是只有 Storybook 截图。",
    ["design tokens", "WCAG", "ARIA", "keyboard navigation", "responsive components"],
    roles(0, 3, 1, 2, 0),
    ["web-platform", "ux-judgment"],
  ),
  node(
    "frontend-performance",
    "frontend",
    "Frontend performance",
    "前端性能",
    "控制加载、渲染、网络和主线程成本，让真实设备上的交互保持及时。",
    "能用 profile 而非猜测定位瓶颈，处理 bundle、缓存、图片、列表和重渲染。",
    "一份前后对比的 Web Vitals/profile，说明优化目标和没有采用的取舍。",
    ["Core Web Vitals", "profiling", "code splitting", "virtualization", "image optimization"],
    roles(0, 3, 1, 0, 0),
    ["react-architecture", "client-data-state"],
  ),
  node(
    "realtime-experience",
    "frontend",
    "Realtime & long-running UX",
    "实时与长任务体验",
    "让流式、异步、可取消的后台工作在界面中可见、可控、可恢复。",
    "能设计 progress、partial result、reconnect、cancel、resume 和最终一致状态。",
    "一个在断网重连和页面刷新后仍能恢复的 SSE/WebSocket 长任务界面。",
    ["SSE", "WebSocket", "streaming", "background jobs", "reconnection"],
    roles(1, 3, 3, 2, 1),
    ["client-data-state", "async-messaging"],
  ),
  node(
    "fullstack-delivery",
    "frontend",
    "End-to-end product delivery",
    "端到端产品交付",
    "从用户问题穿过 UI、API、数据、部署和反馈闭环，独立交付完整结果。",
    "能在各层做够用的判断，主动缩小范围，并对上线后的指标和故障负责。",
    "一个真实用户使用、带监控和迭代记录的完整产品，而不是功能演示。",
    ["React", "TypeScript", "APIs", "SQL", "deployment", "analytics"],
    roles(1, 3, 3, 2, 2),
    ["react-architecture", "backend-services", "testing-strategy", "product-metrics"],
  ),

  // Platform & operations
  node(
    "system-design",
    "platform",
    "System design",
    "系统设计",
    "从需求、规模和失败模式推导架构、接口、数据流和演进路径。",
    "能做容量估算，明确单点、边界和 trade-off，并先选最简单可演进方案。",
    "一份含需求、估算、架构、数据模型、失败处理和替代方案的设计文档。",
    ["capacity estimation", "architecture diagrams", "data flows", "trade-offs", "ADRs"],
    roles(3, 2, 3, 2, 3),
    ["backend-services", "networking-http", "transactions-consistency"],
  ),
  node(
    "distributed-systems",
    "platform",
    "Distributed systems",
    "分布式系统",
    "在网络不可靠、节点独立失败和并发复制下推理系统行为。",
    "能讨论复制、分区、共识、一致性、时钟和重试，而不是只引用 CAP。",
    "对一个真实系统写出故障矩阵，并通过实验验证至少一种网络分区行为。",
    ["replication", "partitioning", "consensus", "consistency", "failure detection"],
    roles(3, 1, 3, 1, 3),
    ["system-design", "async-messaging"],
  ),
  node(
    "cloud-fundamentals",
    "platform",
    "Cloud architecture",
    "云架构",
    "用计算、存储、网络、身份和托管服务组装安全且成本合理的运行环境。",
    "能选择 service boundary，设计 VPC/IAM/secret/backup，并解释 managed service 的锁定与运维取舍。",
    "一套最小权限、可重建、有成本估算和灾备说明的 AWS/GCP 环境。",
    ["AWS", "GCP", "compute", "object storage", "VPC", "IAM"],
    roles(3, 2, 3, 1, 3),
    ["system-design", "identity-security"],
  ),
  node(
    "containers-orchestration",
    "platform",
    "Containers & orchestration",
    "容器与编排",
    "把服务打包成可重复部署的单元，并管理调度、配置、网络和滚动更新。",
    "能写小而安全的镜像，解释 probe/resource/rollout，并诊断 K8s 调度与网络问题。",
    "一个有资源限制、健康检查、滚动更新和故障演练的 Docker/Kubernetes 部署。",
    ["Docker", "Kubernetes", "GKE", "Helm", "service discovery"],
    roles(3, 1, 3, 0, 3),
    ["cloud-fundamentals", "os-concurrency"],
  ),
  node(
    "delivery-automation",
    "platform",
    "CI/CD & infrastructure as code",
    "CI/CD 与基础设施即代码",
    "让代码、配置和基础设施通过可审查、可回滚的自动路径进入生产。",
    "能设计 build/test/security/deploy gates，管理环境差异、迁移和 rollback。",
    "从空环境一键重建并完成一次真实回滚的 Terraform + CI/CD pipeline。",
    ["GitHub Actions", "Terraform", "CI/CD", "artifact registries", "feature flags"],
    roles(3, 2, 3, 0, 3),
    ["cloud-fundamentals", "testing-strategy", "engineering-quality"],
  ),
  node(
    "observability",
    "platform",
    "Observability",
    "可观测性",
    "从指标、日志、trace 和业务事件回答系统现在发生了什么、为什么。",
    "能定义有行动价值的 telemetry，跨服务关联请求，并从用户影响反推诊断。",
    "一个能从告警下钻到 root cause 的 dashboard/trace，而不是日志堆。",
    ["metrics", "logs", "traces", "OpenTelemetry", "Prometheus", "Grafana"],
    roles(3, 2, 3, 1, 3),
    ["backend-services", "cloud-fundamentals"],
  ),
  node(
    "reliability",
    "platform",
    "Reliability engineering",
    "可靠性工程",
    "用 SLO、容量、降级和事故学习管理可接受的失败。",
    "能设 SLI/SLO/error budget，设计超时、重试、熔断、降级，并主持无责复盘。",
    "一次故障演练或真实 incident 的时间线、用户影响、根因和可验证修复。",
    ["SLI/SLO", "error budgets", "incident response", "circuit breakers", "chaos testing"],
    roles(3, 1, 3, 1, 3),
    ["observability", "distributed-systems"],
  ),
  node(
    "performance-capacity",
    "platform",
    "Performance & capacity",
    "性能与容量",
    "用测量和排队直觉改善延迟、吞吐、资源和成本。",
    "能定义 workload，读 p50/p95/p99，找瓶颈，做 load test，并区分纵向与横向扩展。",
    "有基线、profile、负载曲线、成本变化和回归保护的性能优化。",
    ["profiling", "load testing", "latency percentiles", "queuing", "autoscaling"],
    roles(3, 2, 3, 1, 3),
    ["observability", "system-design"],
  ),
  node(
    "platform-security",
    "platform",
    "Platform security & compliance",
    "平台安全与合规",
    "把威胁、数据分类、供应链和监管要求变成架构与运行控制。",
    "能做 threat model，设计 encryption/secrets/audit/retention，并区分合规证明与真实安全。",
    "一份威胁模型及其在 IAM、网络、日志、数据生命周期中的落地证据。",
    ["threat modeling", "encryption", "secrets", "audit", "SOC 2", "HIPAA"],
    roles(2, 1, 3, 2, 3),
    ["identity-security", "cloud-fundamentals", "observability"],
  ),
  node(
    "developer-platforms",
    "platform",
    "Developer platforms & DX",
    "开发者平台与 DX",
    "把重复基础能力做成自助、可靠、有护栏的内部或外部平台。",
    "能找到 paved road 的正确边界，设计 API/SDK/CLI、文档、迁移和 adoption metric。",
    "一个被第二个团队独立采用的平台能力，附 onboarding 时间和支持负担变化。",
    ["SDKs", "CLIs", "internal platforms", "self-service", "golden paths", "documentation"],
    roles(3, 2, 3, 3, 3),
    ["system-design", "api-contracts", "delivery-automation", "ux-judgment"],
  ),

  // AI systems
  node(
    "ml-foundations",
    "ai-systems",
    "ML foundations",
    "机器学习基础",
    "理解数据、目标函数、泛化和误差，让模型结果能被正确解释。",
    "能区分训练/验证/测试，识别 leakage、imbalance、overfit，并为任务选择合适指标。",
    "一个包含基线、数据切分、误差分析和复现实验的 ML notebook/repo。",
    ["supervised learning", "embeddings", "loss functions", "validation", "PyTorch"],
    roles(0, 1, 3, 2, 1),
    ["problem-solving", "experimentation"],
  ),
  node(
    "llm-foundations",
    "ai-systems",
    "LLM foundations",
    "大模型基础",
    "理解 token、attention、context、sampling 和训练阶段如何塑造模型能力与限制。",
    "能解释为什么输出非确定、context 会失效、不同模型/参数如何影响质量、延迟和成本。",
    "一份跨模型、参数和任务的可复现实验，而不是模型排行榜摘录。",
    ["transformers", "tokens", "attention", "sampling", "pre-training", "post-training"],
    roles(0, 1, 3, 3, 2),
    ["ml-foundations"],
  ),
  node(
    "context-engineering",
    "ai-systems",
    "Context & prompt engineering",
    "上下文与提示工程",
    "为模型提供正确指令、状态、示例和边界，使行为稳定且可评估。",
    "能设计结构化 prompt/context，控制 token budget，处理注入和版本，并用 eval 而非直觉迭代。",
    "有版本、测试集和失败分类的 prompt/context pipeline。",
    ["prompt templates", "structured outputs", "few-shot", "context windows", "prompt injection"],
    roles(0, 2, 3, 3, 1),
    ["llm-foundations", "requirements"],
  ),
  node(
    "embeddings-retrieval",
    "ai-systems",
    "Embeddings & retrieval",
    "向量表示与检索",
    "把用户意图匹配到正确证据，权衡召回、精度、延迟和索引成本。",
    "能比较 lexical/dense/hybrid，选择 chunk/index/rerank，并用 retrieval metrics 做误差分析。",
    "一个有标注查询集、Recall@k/nDCG、延迟和索引比较的检索系统。",
    ["embeddings", "BM25", "vector search", "HNSW", "hybrid search", "rerankers"],
    roles(1, 1, 3, 2, 1),
    ["ml-foundations", "data-pipelines"],
  ),
  node(
    "rag",
    "ai-systems",
    "Retrieval-augmented generation",
    "RAG",
    "让生成有可追溯证据、权限边界和可测量的知识覆盖。",
    "能设计 ingestion/chunk/retrieval/rerank/citation，区分 retrieval 与 generation failure。",
    "带权限过滤、引用、离线评估和线上反馈的生产 RAG，而不是 PDF chat demo。",
    ["RAG", "vector databases", "Milvus", "pgvector", "citations", "reranking"],
    roles(1, 2, 3, 3, 1),
    ["embeddings-retrieval", "context-engineering", "identity-security"],
  ),
  node(
    "tool-use",
    "ai-systems",
    "Tool use & structured actions",
    "工具调用与结构化行动",
    "让模型安全地读取和改变外部系统，而不把文本建议误当执行。",
    "能设计 schema、权限、确认、幂等、超时和错误回传，并抵抗恶意工具输出。",
    "一个有 allowlist、审批、审计和失败恢复的 API/MCP tool integration。",
    ["function calling", "JSON Schema", "MCP", "APIs", "sandboxes", "human approval"],
    roles(1, 2, 3, 3, 2),
    ["api-contracts", "context-engineering", "identity-security"],
  ),
  node(
    "agent-orchestration",
    "ai-systems",
    "Agent state & orchestration",
    "Agent 状态与编排",
    "把长任务拆成可暂停、重试、检查和恢复的状态化工作流。",
    "能选择单 agent、workflow 或 multi-agent，定义 state/checkpoint/termination，并处理循环和部分失败。",
    "一个经中断恢复、预算限制和 failure injection 验证的 LangGraph/agent workflow。",
    ["LangGraph", "LangChain", "state machines", "checkpoints", "multi-agent", "workflows"],
    roles(1, 2, 3, 3, 2),
    ["tool-use", "async-messaging", "software-design"],
  ),
  node(
    "ai-evaluation",
    "ai-systems",
    "AI evaluation",
    "AI 评估体系",
    "把主观的“看起来不错”变成覆盖质量、行为、成本和风险的可重复判断。",
    "能构建代表性数据集、rubric/grader、人工校准、回归门槛，并结合 offline/online 指标。",
    "一套能捕获真实失败、与人工判断校准并阻止回归的 eval harness。",
    ["eval datasets", "LLM-as-judge", "human evaluation", "tracing", "regression gates"],
    roles(1, 2, 3, 3, 2),
    ["experimentation", "llm-foundations", "product-metrics"],
  ),
  node(
    "ai-safety",
    "ai-systems",
    "AI safety, trust & guardrails",
    "AI 安全、信任与护栏",
    "控制幻觉、越权、注入、隐私和高风险行动，同时让限制对用户可理解。",
    "能做 threat/risk taxonomy，设计 input/output/action controls、red team、human-in-loop 和 safe fallback。",
    "一份红队结果与对应可测护栏，展示误杀、漏过和用户体验取舍。",
    ["guardrails", "red teaming", "prompt injection", "PII", "moderation", "human-in-the-loop"],
    roles(0, 1, 3, 3, 2),
    ["ai-evaluation", "tool-use", "platform-security"],
  ),
  node(
    "model-serving",
    "ai-systems",
    "Model inference & serving",
    "模型推理与服务",
    "在质量、延迟、吞吐、显存、可用性和成本之间运行模型服务。",
    "能解释 batching/caching/quantization/routing，做容量测试，并处理 cold start 与降级。",
    "一个有吞吐/延迟/成本曲线、autoscaling 和 fallback 的 vLLM/managed endpoint。",
    ["vLLM", "Hugging Face", "Vertex AI", "batching", "quantization", "GPU"],
    roles(2, 0, 3, 2, 3),
    ["llm-foundations", "performance-capacity", "containers-orchestration"],
  ),
  node(
    "llmops",
    "ai-systems",
    "LLMOps",
    "LLMOps",
    "管理模型、prompt、数据、eval、发布、监控和反馈的完整生命周期。",
    "能追溯一次输出使用的版本和数据，做 canary/rollback，监控质量漂移、成本和供应商变化。",
    "从实验到生产可复现、可比较、可回滚的 AI release pipeline。",
    ["LangSmith", "Weights & Biases", "model registry", "tracing", "canary", "versioning"],
    roles(2, 1, 3, 3, 3),
    ["ai-evaluation", "observability", "delivery-automation", "model-serving"],
  ),
  node(
    "multimodal-voice",
    "ai-systems",
    "Multimodal & voice systems",
    "多模态与语音系统",
    "组合文本、图像、音频和实时媒体，处理各模态独有的延迟与质量问题。",
    "能设计 ASR/LLM/TTS 或 vision pipeline，评估端到端延迟、打断、同步和领域质量。",
    "一个有真实噪声/口音/图像分布测试和端到端 latency budget 的系统。",
    ["ASR", "TTS", "vision-language models", "WebRTC", "streaming audio", "CLIP"],
    roles(0, 2, 3, 2, 1),
    ["model-serving", "ai-evaluation", "realtime-experience"],
  ),
  node(
    "feedback-flywheel",
    "ai-systems",
    "Feedback & data flywheels",
    "反馈与数据飞轮",
    "把真实使用中的失败和成功转成更好的数据、eval、prompt、检索或模型决策。",
    "能设计可解释反馈、采样、标注和隐私边界，避免只学习活跃用户或错误代理指标。",
    "一条从 production trace 到标注、eval regression 和发布决定的闭环。",
    ["feedback capture", "annotation", "active learning", "synthetic data", "data governance"],
    roles(0, 1, 3, 3, 2),
    ["ai-evaluation", "data-pipelines", "product-metrics"],
  ),
  node(
    "training-posttraining",
    "ai-systems",
    "Fine-tuning & post-training",
    "微调与后训练",
    "判断何时训练优于 prompt/RAG，并构建数据、训练和评估闭环。",
    "能选择 SFT/PEFT/preference optimization，控制数据质量、compute、overfit 和安全回归。",
    "一个与 prompt/RAG 基线公平比较、包含误差与成本分析的 fine-tuning 实验。",
    ["SFT", "LoRA", "PEFT", "RLHF", "DPO", "synthetic data"],
    roles(0, 0, 2, 2, 1),
    ["ml-foundations", "llm-foundations", "ai-evaluation", "data-pipelines"],
  ),

  // Product leadership
  node(
    "technical-product-fluency",
    "product-leadership",
    "Technical product fluency",
    "技术产品理解力",
    "深入参与架构与实现取舍，同时不替工程团队做局部最优决策。",
    "能读 design doc、追数据流、质疑假设，并把技术限制翻译成用户和商业影响。",
    "一份把架构选项、用户影响、成本、风险和决定连在一起的 decision memo。",
    ["system design", "APIs", "data models", "architecture reviews", "technical trade-offs"],
    roles(1, 1, 2, 3, 3),
    ["system-design", "requirements", "business-value"],
  ),
  node(
    "ai-product-judgment",
    "product-leadership",
    "AI product judgment",
    "AI 产品判断",
    "选择 AI 真正适合的问题，并在概率行为、数据准备和用户信任间定义产品。",
    "能判断 automate/assist/not-AI，定义 quality-latency-cost-safety trade-off 和 human fallback。",
    "一个从 use-case selection、prototype、eval 到 launch criteria 的 AI product brief。",
    ["use-case selection", "data readiness", "AI UX", "human-in-the-loop", "model trade-offs"],
    roles(0, 1, 3, 3, 2),
    ["technical-product-fluency", "llm-foundations", "ai-evaluation", "customer-discovery"],
  ),
  node(
    "platform-product",
    "product-leadership",
    "Platform & developer product management",
    "平台与开发者产品",
    "为多个团队或开发者设计稳定原语、adoption path 和生态边界。",
    "能区分平台与定制项目，设计抽象、API/SDK、版本、迁移、定价或内部 chargeback。",
    "一个被多个独立调用者采用、支持成本可控的平台 roadmap 与 adoption evidence。",
    ["platform strategy", "APIs", "SDKs", "developer experience", "ecosystems", "adoption metrics"],
    roles(0, 1, 2, 3, 2),
    ["developer-platforms", "technical-product-fluency", "prioritization"],
  ),
  node(
    "product-execution",
    "product-leadership",
    "Product execution",
    "产品执行",
    "从 discovery 到 launch 再到 iteration，持续维持目标、范围和团队判断的一致。",
    "能形成小而可验证的切片，清除阻塞，管理变更，并在上线后基于证据继续或停止。",
    "一次完整 launch narrative：问题、选择、范围变化、结果、失败和下一决定。",
    ["discovery", "scoping", "launches", "stakeholder alignment", "iteration"],
    roles(0, 2, 2, 3, 3),
    ["prioritization", "product-metrics", "requirements", "stakeholder-communication"],
  ),

  // Program & field delivery
  node(
    "program-architecture",
    "program-delivery",
    "Program architecture",
    "项目群架构",
    "把战略目标拆成有 owner、接口、里程碑和成功条件的跨团队 workstream。",
    "能选择正确 program boundary，建立 charter/WBS，并识别哪些工作必须作为同一系统管理。",
    "一个含目标、范围、工作流、owner、接口和 success metric 的 program charter。",
    ["program charters", "workstreams", "RACI/DRI", "milestones", "governance"],
    roles(0, 0, 1, 2, 3),
    ["problem-framing", "requirements", "system-design"],
  ),
  node(
    "dependency-management",
    "program-delivery",
    "Dependencies & critical path",
    "依赖与关键路径",
    "让跨团队依赖、交接和资源约束可见，并保护真正决定交付时间的路径。",
    "能区分硬/软依赖，维护 critical path，提前暴露 interface mismatch 与 schedule risk。",
    "一个持续更新的 dependency map，能解释某次计划变化如何传导到最终结果。",
    ["dependency maps", "critical path", "integrated schedules", "handoffs", "capacity"],
    roles(0, 0, 0, 2, 3),
    ["program-architecture"],
  ),
  node(
    "risk-decisions",
    "program-delivery",
    "Risk & decision management",
    "风险与决策管理",
    "在信息不完整时推动可逆决定，升级不可接受风险，并保留决策上下文。",
    "能量化 probability/impact，区分 issue/risk/assumption，设 trigger、owner、mitigation 和 escalation。",
    "一个不是状态表演的 risk register：高风险有触发器、行动、owner 和关闭证据。",
    ["risk registers", "decision logs", "trade-offs", "escalation", "scenario planning"],
    roles(0, 0, 1, 2, 3),
    ["dependency-management", "technical-product-fluency"],
  ),
  node(
    "operating-cadence",
    "program-delivery",
    "Operating cadence & information flow",
    "运行节奏与信息流",
    "建立最少但足够的机制，让决策、阻塞和承诺在组织中及时流动。",
    "能设计 review/standup/dashboard 的目的和退出条件，删除不能改变决定的汇报。",
    "一套让 meeting time 下降、风险更早暴露、决策 latency 更短的 operating mechanism。",
    ["status reviews", "dashboards", "decision hygiene", "meeting design", "documentation"],
    roles(0, 0, 0, 2, 3),
    ["risk-decisions", "product-metrics"],
  ),
  node(
    "release-readiness",
    "program-delivery",
    "Release & operational readiness",
    "发布与运营就绪",
    "确认产品、系统、支持、安全、数据和业务都能承受上线与回退。",
    "能运行 readiness review，明确 SLO、runbook、on-call、migration、rollback、support 和 launch criteria。",
    "一次带 go/no-go 决策、演练证据和上线后复盘的 release。",
    ["launch checklists", "runbooks", "go/no-go", "rollbacks", "on-call", "change management"],
    roles(2, 2, 2, 2, 3),
    ["reliability", "delivery-automation", "risk-decisions"],
  ),
  node(
    "vendor-capacity",
    "program-delivery",
    "Vendors, capacity & external partners",
    "供应商、容量与外部伙伴",
    "协调云、模型、硬件、数据或实施伙伴，使外部依赖达到内部交付标准。",
    "能定义 SLA/KPI、容量预测、商业与技术验收、升级路径和退出方案。",
    "一份 provider scorecard 与容量/成本情景，能支持续约、扩容或迁移决定。",
    ["SLAs", "capacity planning", "procurement", "provider scorecards", "partner governance"],
    roles(0, 0, 1, 2, 3),
    ["performance-capacity", "risk-decisions", "business-value"],
  ),
  node(
    "stakeholder-communication",
    "program-delivery",
    "Stakeholder & executive communication",
    "利益相关方与高层沟通",
    "为工程、研究、设计、销售和高层提供各自能据以行动的同一事实版本。",
    "能写结论先行的 memo/status，明确 ask/decision/risk，并在没有汇报权时建立共识。",
    "一页 executive update：结果、变化、风险、选项和所需决定，没有活动流水账。",
    ["writing", "executive updates", "influence", "facilitation", "conflict resolution"],
    roles(1, 2, 2, 3, 3),
    ["problem-framing"],
  ),
  node(
    "field-deployment",
    "program-delivery",
    "Forward-deployed discovery & integration",
    "客户现场发现与集成",
    "进入客户工作流，连接真实系统，把一次性交付提炼成可复用产品能力。",
    "能画 current/future workflow，处理脏数据、权限、集成和现场反馈，同时守住 product boundary。",
    "一个从客户问题到生产集成再到平台化抽象的案例，含采用和业务结果。",
    ["workflow mapping", "APIs", "enterprise integrations", "solution architecture", "customer delivery"],
    roles(1, 2, 3, 3, 3),
    ["customer-discovery", "api-contracts", "technical-product-fluency", "product-execution"],
  ),
  node(
    "adoption-change",
    "program-delivery",
    "Adoption & change management",
    "采用与变革管理",
    "让新系统进入真实组织行为，处理培训、激励、流程和责任变化。",
    "能识别 adopter/champion/blocker，设计 rollout、enablement、反馈与 adoption metric。",
    "一个从 pilot 到持续使用的 rollout，展示行为采用而不只是账号开通。",
    ["pilots", "rollouts", "enablement", "adoption metrics", "organizational change"],
    roles(0, 1, 1, 3, 3),
    ["field-deployment", "product-metrics", "stakeholder-communication"],
  ),
] as const;

export const ROLE_PROFILES: Readonly<Record<CapabilityRole, {
  title: string;
  titleZh: string;
  mission: string;
  missionEn: string;
  hiringSignal: string;
  hiringSignalEn: string;
}>> = {
  backend: {
    title: "Backend Engineer",
    titleZh: "后端工程师",
    mission: "把业务和平台能力做成可靠、可演进、可运维的服务与数据系统。",
    missionEn: "Turn business and platform capabilities into reliable, evolvable, operable services and data systems.",
    hiringSignal: "湾区 JD 的高频组合是 API + 数据 + 分布式基础 + 性能/可靠性 + 云上 ownership。",
    hiringSignalEn: "Bay Area postings repeatedly combine APIs, data, distributed fundamentals, performance/reliability, and cloud ownership.",
  },
  fullstack: {
    title: "Full-stack / Product Engineer",
    titleZh: "全栈 / 产品工程师",
    mission: "跨用户体验和生产后端交付完整产品，用短反馈环验证价值。",
    missionEn: "Ship complete products across user experience and production backend, using short feedback loops to validate value.",
    hiringSignal: "高频组合是 React/TypeScript + API/SQL + 端到端 shipping + product judgment；AI 公司还要求 agent UX。",
    hiringSignalEn: "The recurring bundle is React/TypeScript, APIs/SQL, end-to-end shipping, and product judgment; AI companies add agent UX.",
  },
  ai: {
    title: "AI / Applied AI Engineer",
    titleZh: "AI / 应用 AI 工程师",
    mission: "把模型、数据、工具和软件系统组合成可评估、可靠且成本可控的 AI 产品。",
    missionEn: "Combine models, data, tools, and software into AI products that are evaluable, reliable, and cost-controlled.",
    hiringSignal: "高频组合已从 prompt/RAG 扩展到 agents、evals、observability、serving 和 production reliability。",
    hiringSignalEn: "Demand has expanded beyond prompting and RAG to agents, evals, observability, serving, and production reliability.",
  },
  pm: {
    title: "Product / Technical PM",
    titleZh: "产品经理 / 技术产品经理",
    mission: "选择值得解决的问题，连接用户价值、AI 能力、工程约束与商业结果。",
    missionEn: "Choose worthwhile problems and connect user value, AI capability, engineering constraints, and business outcomes.",
    hiringSignal: "AI PM 的核心不是会写 PRD，而是 use-case judgment、技术深度、eval/metrics 和 0→1 决策证据。",
    hiringSignalEn: "AI PM hiring centers on use-case judgment, technical depth, evals/metrics, and evidence of 0-to-1 decisions—not PRD writing.",
  },
  tpm: {
    title: "Technical Program Manager",
    titleZh: "技术项目群经理",
    mission: "让跨团队、高依赖、高风险的技术系统从目标走到可运营结果。",
    missionEn: "Move cross-team, dependency-heavy, high-risk technical systems from intent to operable outcomes.",
    hiringSignal: "AI TPM 高频要求 infrastructure fluency、critical path、风险、容量、可靠性和无直接汇报权的推进能力。",
    hiringSignalEn: "AI TPM postings emphasize infrastructure fluency, critical paths, risk, capacity, reliability, and influence without authority.",
  },
} as const;

export const CAPABILITY_SOURCES = [
  {
    label: "Local corpus: 566 crawled JDs, including 241 Bay Area postings",
    note: "Backend、Full-stack、AI Engineer 的主要需求信号；2026-08-25 快照。",
  },
  {
    label: "OpenAI — Product Engineer, Full Stack, Agents",
    url: "https://openai.com/careers/product-engineer-full-stack-agents-san-francisco/",
    note: "端到端 agent product engineering、异步状态、可靠性和企业体验。",
  },
  {
    label: "OpenAI — Product Manager, API Agents",
    url: "https://openai.com/careers/product-manager-api-agents-san-francisco/",
    note: "AI PM 的 developer platform、模型能力、用户问题和安全取舍。",
  },
  {
    label: "Anthropic — Software Engineer, Research Tools",
    url: "https://www.anthropic.com/careers/jobs/4981828008",
    note: "研究工具、内部平台、product thinking 和跨研究/工程协作。",
  },
  {
    label: "Microsoft AI — Technical Program Manager, Infrastructure",
    url: "https://microsoft.ai/job/technical-program-manager-infrastructure/",
    note: "AI infrastructure TPM、训练/推理平台、指标、风险和跨团队交付。",
  },
  {
    label: "Box — Product Manager II, AI Evaluations",
    url: "https://careers.box.com/en/jobs/8039877/product-manager-ii-ai-evaluations/",
    note: "hands-on eval、Python/SQL、模型生命周期、provider partnership。",
  },
  {
    label: "Scale AI — AI Product Manager, Coding/Multimodal",
    url: "https://scale.com/careers/4609736005",
    note: "较早期 AI PM 的执行、数据产品、客户项目和跨职能能力。",
  },
] as const;

export function demandFor(node: CapabilityNode, role: CapabilityRole): CapabilityDemand | null {
  const value = node.roles[role];
  return value === 3 ? "core" : value === 2 ? "recurring" : value === 1 ? "adjacent" : null;
}

export function unlockedBy(nodeId: string): CapabilityNode[] {
  return CAPABILITY_NODES.filter((candidate) => candidate.prerequisites.includes(nodeId));
}
