/**
 * Host → the icon file for it under `public/robin/logos/`.
 *
 * Generated by scripts/refresh-shelf-logos.mjs. Do not edit by hand: the files
 * and this map are written together, and a name here without a file behind it
 * is a broken image on either shelf.
 *
 * A host that is absent is not a bug. Some sites publish nothing usable, and
 * the shelf has always been readable without an icon — it falls back to the
 * host name, which is what it showed before any of these existed.
 */
export const SHELF_LOGOS: Readonly<Record<string, string>> = {
  "ads.tiktok.com": "ads.tiktok.com.ico",
  "anthropic.com": "anthropic.com.png",
  "apps.apple.com": "apps.apple.com.png",
  "canvasui.dev": "canvasui.dev.svg",
  "claude.ai": "claude.ai.ico",
  "coursera.org": "coursera.org.png",
  "craft.wild.as": "craft.wild.as.svg",
  "cs50.harvard.edu": "cs50.harvard.edu.ico",
  "cursor.com": "cursor.com.svg",
  "dataintensive.net": "dataintensive.net.ico",
  "deck.gallery": "deck.gallery.svg",
  "developer.apple.com": "developer.apple.com.svg",
  "developer.mozilla.org": "developer.mozilla.org.svg",
  "docs.github.com": "docs.github.com.png",
  "docs.pytest.org": "docs.pytest.org.ico",
  "facebook.com": "facebook.com.png",
  "fastapi.tiangolo.com": "fastapi.tiangolo.com.png",
  "figma.com": "figma.com.svg",
  "freecodecamp.org": "freecodecamp.org.png",
  "fullstackopen.com": "fullstackopen.com.png",
  "github.com": "github.com.svg",
  "godaddy.com": "godaddy.com.ico",
  "logosystem.co": "logosystem.co.png",
  "loops.so": "loops.so.png",
  "mixpanel.com": "mixpanel.com.svg",
  "mnmm.xyz": "mnmm.xyz.svg",
  "modelcontextprotocol.io": "modelcontextprotocol.io.png",
  "noiced.com": "noiced.com.svg",
  "owasp.org": "owasp.org.ico",
  "packaging.python.org": "packaging.python.org.png",
  "posthog.com": "posthog.com.svg",
  "producthunt.com": "producthunt.com.png",
  "reactbits.dev": "reactbits.dev.png",
  "recent.design": "recent.design.svg",
  "reddit.com": "reddit.com.png",
  "revenuecat.com": "revenuecat.com.svg",
  "roadmap.sh": "roadmap.sh.png",
  "sensortower.com": "sensortower.com.svg",
  "sre.google": "sre.google.png",
  "supabase.com": "supabase.com.png",
  "superwall.com": "superwall.com.svg",
  "theodinproject.com": "theodinproject.com.svg",
  "training.linuxfoundation.org": "training.linuxfoundation.org.png",
  "trends.google.com": "trends.google.com.ico",
  "typescriptlang.org": "typescriptlang.org.png",
  "unicorn.studio": "unicorn.studio.png",
  "vwad.owasp.org": "vwad.owasp.org.svg",
  "x.com": "x.com.ico",
  "youtube.com": "youtube.com.png",
};

/** The public URL for a host's icon, or null when it has none. */
export function shelfLogo(host: string): string | null {
  const normalized = host.toLowerCase().replace(/\.$/, "").replace(/^www\./, "");
  const file = SHELF_LOGOS[normalized] ?? SHELF_LOGOS[`www.${normalized}`];
  return file ? `/robin/logos/${file}` : null;
}
