/**
 * Host → the icon file for it under `public/robin/logos/`.
 *
 * Generated by scripts/refresh-shelf-logos.mjs. Do not edit by hand: the files
 * and this map are written together, and a name here without a file behind it
 * is a broken image on the Learning Hub.
 *
 * A host that is absent is not a bug. Some sites publish nothing usable, and
 * the shelf has always been readable without an icon — it falls back to the
 * host name, which is what it showed before any of these existed.
 */
export const SHELF_LOGOS: Readonly<Record<string, string>> = {
  "canvasui.dev": "canvasui.dev.svg",
  "craft.wild.as": "craft.wild.as.svg",
  "dataintensive.net": "dataintensive.net.ico",
  "deck.gallery": "deck.gallery.svg",
  "developer.mozilla.org": "developer.mozilla.org.svg",
  "docs.github.com": "docs.github.com.png",
  "docs.pytest.org": "docs.pytest.org.ico",
  "fastapi.tiangolo.com": "fastapi.tiangolo.com.png",
  "fullstackopen.com": "fullstackopen.com.png",
  "github.com": "github.com.svg",
  "logosystem.co": "logosystem.co.png",
  "mnmm.xyz": "mnmm.xyz.svg",
  "noiced.com": "noiced.com.svg",
  "packaging.python.org": "packaging.python.org.png",
  "reactbits.dev": "reactbits.dev.png",
  "recent.design": "recent.design.svg",
  "sre.google": "sre.google.png",
  "www.freecodecamp.org": "www.freecodecamp.org.png",
  "www.typescriptlang.org": "www.typescriptlang.org.png",
  "www.unicorn.studio": "www.unicorn.studio.png",
  "www.youtube.com": "www.youtube.com.png",
};

/** The public URL for a host's icon, or null when it has none. */
export function shelfLogo(host: string): string | null {
  const file = SHELF_LOGOS[host];
  return file ? `/robin/logos/${file}` : null;
}
