#!/usr/bin/env python3
"""Refresh official FSO titles/links only; no course prose is copied.
Run from the repository root: python3 scripts/refresh-fullstack-open.py
"""
from concurrent.futures import ThreadPoolExecutor
from html.parser import HTMLParser
import json
from pathlib import Path
import re
from urllib.request import urlopen

BASE = "https://fullstackopen.com"


class Outline(HTMLParser):
    def __init__(self, html):
        super().__init__()
        self.links = []
        self.headings = []
        self.active = []
        self.feed(html)

    def handle_starttag(self, tag, attrs):
        if tag == "img":
            self.handle_data(dict(attrs).get("alt", ""))
        if tag == "a" or re.fullmatch(r"h[1-6]", tag):
            self.active.append([tag, dict(attrs).get("href", ""), ""])

    def handle_data(self, data):
        for item in self.active:
            item[2] += data

    def handle_endtag(self, tag):
        if self.active and self.active[-1][0] == tag:
            _, href, text = self.active.pop()
            text = " ".join(text.split())
            (self.links if tag == "a" else self.headings).append((href, text))


def fetch(url):
    with urlopen(url, timeout=45) as response:
        return response.read().decode("utf-8")


def part_outline(part):
    path = f"/en/part{part}"
    outline = Outline(fetch(BASE + path))
    links = dict((href, re.sub(r"^[a-z] ", "", title))
                 for href, title in outline.links
                 if href.startswith(path + "/") and "legacy" not in href)
    if links:
        sections = []
        for href, title in links.items():
            page = Outline(fetch(BASE + href))
            exercises = {}
            for _, text in page.headings:
                number = re.match(rf"^{part}\.\d+", text)
                if number:
                    # Alternative implementations share a number: follow the
                    # first (current Zustand) path, not both implementations.
                    exercises.setdefault(number[0], text)
            sections.append([part, href, title, list(exercises.values())])
        return sections
    # Advanced parts now live on mooc.fi. Keep their actual landing URL and
    # whole-part granularity rather than inventing an exercise syllabus.
    data = json.loads(fetch(f"{BASE}/page-data/en/part{part}/page-data.json"))
    intro = Outline(data["result"]["data"]["markdownRemark"]["html"])
    moved = [href for href, _ in intro.links if href.startswith("https://courses.mooc.fi/")]
    if not moved:
        raise ValueError(f"Part {part}: no sections or official migration link")
    return [[part, moved[0], f"Part {part}", []]]


def main():
    home = fetch(BASE + "/en/")
    parts = sorted({int(p) for p in re.findall(r'href="/en/part(\d+)"', home)})
    if not parts or parts[0] != 0:
        raise ValueError("Official part directory missing")
    with ThreadPoolExecutor(max_workers=4) as pool:
        sections = [section for group in pool.map(part_outline, parts) for section in group]
    titles = {int(match[1]): re.sub(r"^Part \d+\s*", "", title)
              for href, title in Outline(home).links
              if (match := re.fullmatch(r"/en/part(\d+)", href))}
    for section in sections:
        if section[1].startswith("https:"):
            section[2] = titles.get(section[0]) or section[2]
    output = "// Generated by scripts/refresh-fullstack-open.py from the official course.\n"
    output += "// Titles and links only. Migrated mooc.fi courses are whole-part checkpoints.\n"
    output += "export const FSO_SECTIONS: ReadonlyArray<readonly [number, string, string, readonly string[]]> = [\n"
    output += "".join("  " + json.dumps(section, ensure_ascii=False) + ",\n" for section in sections)
    output += "];\n"
    Path("extension/robin/fullstack-open-catalog.ts").write_text(output)
    print(f"{len(parts)} parts, {len(sections)} sections, {sum(len(s[3]) for s in sections)} exercise checkpoints")


if __name__ == "__main__":
    main()
